apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: test
spec:
  type: NodePort
  ports:
  - nodePort: 30200
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: lb1
  # The label of the pod should be the selector for the service

  // pingapp