apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
  labels:
    name: lb
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128m"
        cpu: "100m"
    ports:
      - containerPort: 80
  - name: pingapp
    image: jpalaparthi/pingapp
    ports:
      - containerPort: 50080


# Create a pod that must run pingapp/ or any other app you create

# create a service to access that app

# access it with LoadBalancer , NodePort and ClusterIP

# Cannot accesss through ClusterIP check that
