apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  namespace: test
  labels:
    app: nginx
spec:
  minReadySeconds: 30
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:perl
          ports:
            - containerPort: 80