apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test
  labels:
    currency: Rupee
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: db-creds
            key: username  
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-creds
            key: password  
      - name: CURRENCY
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['currency']
    ports:
      - containerPort: 80