apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-file-configmap
  namespace: test
  labels:
    currency: Rupee
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
   
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath:  /root
        name: nginxconfig
  volumes:
    - name: nginxconfig
      configMap:
        name: nginx-conf
        items:
        - key: nginx.conf
          path: nginx.conf