apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test
  labels:
    name: lb
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "255m"
    ports:
      - containerPort: 80
